language: java
jdk:
  - openjdk11

env:
  - TERM=dumb

git:
  clone: false

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
#We need it because otherwise Travis CI injects an awkward './gradlew assemble' step into the CI workflow
#We want to control and decide what Gradle tasks are executed
install:
  - true

before_script:
  - |
    # для master ветки необходим кастомный git clone для возможности выпуска релиза
    if [ $TRAVIS_PULL_REQUEST == "false" ]; then
        git config --global user.email "SvcReleaserBackend@yoomoney.ru"
        git config --global user.name "yoomoney-robot"
        echo $GIT_KEY | openssl base64 -A -d >> ~/.ssh/git_key
        cat ~/.ssh/git_key
        export ORG_GRADLE_PROJECT_signingKey=$(echo $PUBLISH_GPG_KEY | openssl base64 -A -d)
        chmod 400 ~/.ssh/git_key
        eval `ssh-agent -s`
        echo "echo $GIT_KEY_PASSPHRASE" >> $HOME/passphrase
        chmod 700 $HOME/passphrase
        export DISPLAY=":0.0"
        cat ~/.ssh/git_key | SSH_ASKPASS="$HOME/passphrase" ssh-add -
        git clone --depth=50 --branch=$TRAVIS_BRANCH git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        cd $TRAVIS_REPO_SLUG
        git checkout -f $TRAVIS_BRANCH
        export GIT_PRIVATE_SSH_KEY_PATH=~/.ssh/git_key
    fi

if: commit_message !~ /(\[Gradle Release Plugin\])/

jobs:
  include:
    - stage: release
      script:
        - |
          ./gradlew -b build.gradle preRelease --debug  --stacktrace --refresh-dependencies -D"gradle.publish.key"=$GRADLE_PUBLISH_KEY -D"gradle.publish.secret"=$GRADLE_PUBLISH_SECRET

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
